In [51]:
import pandas as pd

import random 

import numpy as np

In [52]:

# 1¿Qué diferencia hay entre una Serie y un DataFrame?

In [53]:

#2. Momento de trabajar con Series. Contesta a las siguientes preguntas:

#2.A Crea dos listas:

#Una que se llame "valores" que tenga 7 números aleatorios.

#Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana
import random

# Crear una lista llamada "valores" con 7 números aleatorios
valores = np.random.randint(1,100,7).tolist ()

# Crear una lista llamada "indices" con 7 strings que se llamen como los días de la semana
indices = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]

print("Valores:", valores)
print("Indices:", indices)


Valores: [38, 36, 40, 95, 34, 64, 13]
Indices: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']


In [54]:
#2.A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

# Crear la Serie
serie = pd.Series(valores, index=indices)

# Imprimir la Serie
print("Serie:")
print(serie)

Serie:
Lunes        38
Martes       36
Miércoles    40
Jueves       95
Viernes      34
Sábado       64
Domingo      13
dtype: int64


In [55]:
# 2. C A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez

In [56]:
# Listas de ejemplo
valores = [34, 67, 12, 89, 45, 78, 23]
indices = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]

# Crear un diccionario usando un bucle for y el método zip
diccionario = {indice: valor for indice, valor in zip(indices, valores)}

print(diccionario)

{'Lunes': 34, 'Martes': 67, 'Miércoles': 12, 'Jueves': 89, 'Viernes': 45, 'Sábado': 78, 'Domingo': 23}


In [57]:
#2D.Crea una Serie con el diccionario creado en el punto anterior.

import pandas as pd

# Listas de ejemplo
valores = [34, 67, 12, 89, 45, 78, 23]
indices = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]

# Crear un diccionario usando un bucle for y el método zip
diccionario = {indice: valor for indice, valor in zip(indices, valores)}

# Crear una Serie de pandas con el diccionario
serie = pd.Series(diccionario)

print(serie)


Lunes        34
Martes       67
Miércoles    12
Jueves       89
Viernes      45
Sábado       78
Domingo      23
dtype: int64


In [58]:
#2.E ¿Qué forma tiene esta última Serie?
forma = serie.shape
print("Serie:")
print(serie)
print("\nForma de la Serie:", forma)

Serie:
Lunes        34
Martes       67
Miércoles    12
Jueves       89
Viernes      45
Sábado       78
Domingo      23
dtype: int64

Forma de la Serie: (7,)


In [59]:
#2.F Qué tipo de datos tiene?

tipo_datos = serie.dtype
print("Serie:")
print(serie)
print("\nTipo de datos de la Serie:", tipo_datos)

Serie:
Lunes        34
Martes       67
Miércoles    12
Jueves       89
Viernes      45
Sábado       78
Domingo      23
dtype: int64

Tipo de datos de la Serie: int64


In [60]:
#2.G ¿Qué tamaño tiene?
tamaño = serie.size

print("Serie:")
print(serie)
print("\nTamaño de la Serie:", tamaño)

Serie:
Lunes        34
Martes       67
Miércoles    12
Jueves       89
Viernes      45
Sábado       78
Domingo      23
dtype: int64

Tamaño de la Serie: 7


In [61]:
#2.H ¿Cuáles son los índices de la Serie?

# Crear una Serie de pandas con las listas de valores e índices
serie = pd.Series(valores, index=indices)

# Imprimir los índices de la Serie
print("Índices de la Serie:")
print(serie.index)

Índices de la Serie:
Index(['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado',
       'Domingo'],
      dtype='object')


In [62]:
#2.H ¿Cuáles son los valores de la Serie?
# Imprimir los valores de la Serie
print("Valores de la Serie:")
print(serie.values)

Valores de la Serie:
[34 67 12 89 45 78 23]


In [63]:
#2.I valor para el lunes
# Extraer el valor para el índice "Lunes"
valor_lunes = serie["Lunes"]

# Imprimir el valor correspondiente al índice "Lunes"
print("Valor para el índice 'Lunes':", valor_lunes)

Valor para el índice 'Lunes': 34


In [64]:
#2.J Extraer los valores para los índices "lunes", "martes" y "miércoles"
# Extraer los valores para los índices "lunes", "martes" y "miércoles"
valores_lunes_martes_miercoles = serie[["Lunes", "Martes", "Miércoles"]]

# Imprimir los valores correspondientes a los índices "lunes", "martes" y "miércoles"
print("Valores para los índices 'Lunes', 'Martes' y 'Miércoles':")
print(valores_lunes_martes_miercoles)

Valores para los índices 'Lunes', 'Martes' y 'Miércoles':
Lunes        34
Martes       67
Miércoles    12
dtype: int64


In [65]:
#2.k Extrae el valor para el índice "lunes" y "domingo".
# Extraer los valores para los índices "lunes" y "domingo"
valores_lunes_domingo = serie[["Lunes", "Domingo"]]

# Imprimir los valores correspondientes a los índices "lunes" y "domingo"
print("Valores para los índices 'Lunes' y 'Domingo':")
print(valores_lunes_domingo)

Valores para los índices 'Lunes' y 'Domingo':
Lunes      34
Domingo    23
dtype: int64


In [66]:
#3. DataFrame
#3.A Crea un array de dos dimensiones con 4 filas y 3 columnas.

import numpy as np

# Crear un array de dos dimensiones con 4 filas y 3 columnas
array_dos_dimensiones = np.random.randint(0, 101, size=(4, 3))

# Imprimir el array de dos dimensiones
print("Array de dos dimensiones:")
print(array_dos_dimensiones)

Array de dos dimensiones:
[[ 74  42  82]
 [ 38  75 100]
 [  5   4  60]
 [ 83  90  72]]


In [67]:
#3.B Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".
import numpy as np
import pandas as pd
# Crear un DataFrame con nombres de columnas
df = pd.DataFrame(array_dos_dimensiones, columns=["España", "Francia", "Italia"])

# Imprimir el DataFrame
print("DataFrame:")
print(df)

DataFrame:
   España  Francia  Italia
0      74       42      82
1      38       75     100
2       5        4      60
3      83       90      72


In [68]:
import pandas as pd

# Cargar el archivo CSV en un DataFrame
df = pd.read_csv("Pair Pandas medallas.csv", encoding="utf-8")

# Imprimir el DataFrame
print("DataFrame:")
print(df)
df.head()

DataFrame:
   Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235


Unnamed: 0           País   Oro  Plata  Bronce
0           1          China  1473    994     720
1           2          Japón  1032   1037     985
2           3  Corea del Sur   745    663     827
3           4           Irán   179    181     197
4           5     Kazajistán   155    158     224

In [69]:
#3.D Usando el loc extrae todas las columnas de la fila de Tailandia

# Usar loc para seleccionar todas las columnas de la fila de Tailandia
fila_tailandia = df.loc[df['País'] == 'Tailandia']

# Imprimir la fila de Tailandia
print("Fila de Tailandia:")
print(fila_tailandia)

Fila de Tailandia:
   Unnamed: 0       País  Oro  Plata  Bronce
6           7  Tailandia  132    175     278


In [79]:
fila_tailandia.loc[df.País=="Tailandia"]

Unnamed: 0       País  Oro  Plata  Bronce
6           7  Tailandia  132    175     278

In [70]:
#3.E Usando el loc extrae todas las columnas de China e Irán.
filas_china_iran = df.loc[df['País'].isin(['China', 'Irán'])]

# Imprimir las filas de China e Irán
print("Filas de China e Irán:")
print(filas_china_iran)

Filas de China e Irán:
   Unnamed: 0   País   Oro  Plata  Bronce
0           1  China  1473    994     720
3           4   Irán   179    181     197


In [82]:
fila_china_iran = df.loc[(df["País"] == "China") | (df["País"] == "Irán")]

# Imprimir las filas de China e Irán
print("Filas de China e Irán:")
print(filas_china_iran)

Filas de China e Irán:
   Unnamed: 0   País   Oro  Plata  Bronce
0           1  China  1473    994     720
3           4   Irán   179    181     197


In [71]:
# 3.F
# Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
datos_china_iran = df.loc[df['País'].isin(['China', 'Irán']), ['País', 'Oro', 'Plata', 'Bronce']]

# Imprimir los datos de "Oro", "Plata" y "Bronce" de China e Irán
print("Datos de 'Oro', 'Plata' y 'Bronce' de China e Irán:")
print(datos_china_iran)

Datos de 'Oro', 'Plata' y 'Bronce' de China e Irán:
    País   Oro  Plata  Bronce
0  China  1473    994     720
3   Irán   179    181     197


In [72]:
#3.G Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
# Obtener el índice de la fila correspondiente a India
indice_india = df.index[df['País'] == 'India'][0]

# Usar iloc para extraer la fila de India y todas las columnas
info_india = df.iloc[indice_india]

# Imprimir la información de la India
print("Información de la India:")
print(info_india)

Información de la India:
Unnamed: 0        6
País          India
Oro             154
Plata           202
Bronce          315
Name: 5, dtype: object


In [73]:
#3.H Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.
paises_posiciones_impares = df.iloc[1::2]

# Imprimir los países en posiciones impares
print("Países en posiciones impares:")
print(paises_posiciones_impares)

Países en posiciones impares:
   Unnamed: 0             País   Oro  Plata  Bronce
1           2            Japón  1032   1037     985
3           4             Irán   179    181     197
5           6            India   154    202     315
7           8        Indonesia   112    131     240
9          10  Corea del Norte    91    120     235


In [74]:
#3.I selecciona unicamente las columnas "Oro", "Plata" y "Bronce".
datos_impares = paises_posiciones_impares[['País','Oro', 'Plata', 'Bronce']]
print("Datos de 'Oro', 'Plata' y 'Bronce' de países en posiciones impares:")
print(datos_impares)

Datos de 'Oro', 'Plata' y 'Bronce' de países en posiciones impares:
              País   Oro  Plata  Bronce
1            Japón  1032   1037     985
3             Irán   179    181     197
5            India   154    202     315
7        Indonesia   112    131     240
9  Corea del Norte    91    120     235


In [85]:
paises_posiciones_impares = df.iloc[1::2, 2:4]
paises_posiciones_impares

Oro  Plata
1  1032   1037
3   179    181
5   154    202
7   112    131
9    91    120

In [75]:
#3.J ¿Qué país consiguió más de 200 medallas de oro?
# Filtrar las filas donde el número de medallas de oro sea mayor que 200
paises_mas_200_oro = df[df['Oro'] > 200]

# Imprimir los países con más de 200 medallas de oro
print("Países con más de 200 medallas de oro:")
print(paises_mas_200_oro)

# Obtener el país con el mayor número de medallas de oro
pais_max_oro = paises_mas_200_oro.loc[paises_mas_200_oro['Oro'].idxmax(), 'País']

# Imprimir el país que ha conseguido más de 200 medallas de oro
print("El país que ha conseguido más de 200 medallas de oro es:", pais_max_oro)

Países con más de 200 medallas de oro:
   Unnamed: 0           País   Oro  Plata  Bronce
0           1          China  1473    994     720
1           2          Japón  1032   1037     985
2           3  Corea del Sur   745    663     827
El país que ha conseguido más de 200 medallas de oro es: China


In [88]:
paises_mas_200_oro = df.loc[df['Oro'] > 200]
paises_mas_200_oro

Unnamed: 0           País   Oro  Plata  Bronce  total
0           1          China  1473    994     720   3187
1           2          Japón  1032   1037     985   3054
2           3  Corea del Sur   745    663     827   2235

In [76]:
#3. K ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
# Filtrar las filas donde el número de medallas de oro sea mayor que 200 y el número de medallas de plata sea mayor que 1000
paises_mas_200_oro_1000_plata = df[(df['Oro'] > 200) & (df['Plata'] > 1000)]

# Imprimir los países que cumplen con las condiciones
print("Países con más de 200 medallas de oro y más de 1000 medallas de plata:")
print(paises_mas_200_oro_1000_plata)

# Obtener el país que tiene el mayor número de medallas de oro y plata dentro de esos países filtrados
pais_max_oro_1000_plata = paises_mas_200_oro_1000_plata.loc[
    (paises_mas_200_oro_1000_plata['Oro'] + paises_mas_200_oro_1000_plata['Plata']).idxmax(), 'País']

# Imprimir el país que ha conseguido más de 200 medallas de oro y más de 1000 medallas de plata
print("El país que ha conseguido más de 200 medallas de oro y más de 1000 medallas de plata es:", pais_max_oro_1000_plata)

Países con más de 200 medallas de oro y más de 1000 medallas de plata:
   Unnamed: 0   País   Oro  Plata  Bronce
1           2  Japón  1032   1037     985
El país que ha conseguido más de 200 medallas de oro y más de 1000 medallas de plata es: Japón


In [92]:
paises_mas_200_oro_1000_plata = df.loc[(df['Oro'] > 200) & (df['Plata'] > 1000)]
print("Países con más de 200 medallas de oro y más de 1000 medallas de plata:")
print(paises_mas_200_oro_1000_plata)

Países con más de 200 medallas de oro y más de 1000 medallas de plata:
   Unnamed: 0   País   Oro  Plata  Bronce  total
1           2  Japón  1032   1037     985   3054


In [77]:
#3. l ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

paises_mas_200_oro_o_700_bronce = df[(df['Oro'] > 200) | (df['Bronce'] > 700)]

# Imprimir los países que cumplen con las condiciones
print("Países con más de 200 medallas de oro o más de 700 medallas de bronce:")
print(paises_mas_200_oro_o_700_bronce)

# Obtener el país que tiene el mayor número de medallas de oro o bronce dentro de esos países filtrados,donde idxmax es utiliza para encontrar el índice del primer valor máximo en una serie o DataFrame.
pais_max_oro_o_700_bronce = paises_mas_200_oro_o_700_bronce.loc[
    (paises_mas_200_oro_o_700_bronce['Oro'] + paises_mas_200_oro_o_700_bronce['Bronce']).idxmax(), 'País']

# Imprimir el país que ha conseguido más de 200 medallas de oro o más de 700 medallas de bronce
print("El país que ha conseguido más de 200 medallas de oro o más de 700 medallas de bronce es:", pais_max_oro_o_700_bronce)

Países con más de 200 medallas de oro o más de 700 medallas de bronce:
   Unnamed: 0           País   Oro  Plata  Bronce
0           1          China  1473    994     720
1           2          Japón  1032   1037     985
2           3  Corea del Sur   745    663     827
El país que ha conseguido más de 200 medallas de oro o más de 700 medallas de bronce es: China


In [78]:
#3.M Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.
import pandas as pd

# Supongamos que 'df' es tu DataFrame cargado previamente desde el archivo CSV

# Calcular la suma de medallas de oro, plata y bronce para cada país
df['total'] = df[['Oro', 'Plata', 'Bronce']].sum(axis=1)

# Imprimir el DataFrame con la nueva columna "total"
print("DataFrame con la nueva columna 'total':")
print(df)

DataFrame con la nueva columna 'total':
   Unnamed: 0             País   Oro  Plata  Bronce  total
0           1            China  1473    994     720   3187
1           2            Japón  1032   1037     985   3054
2           3    Corea del Sur   745    663     827   2235
3           4             Irán   179    181     197    557
4           5       Kazajistán   155    158     224    537
5           6            India   154    202     315    671
6           7        Tailandia   132    175     278    585
7           8        Indonesia   112    131     240    483
8           9     China Taipéi    99    144     276    519
9          10  Corea del Norte    91    120     235    446
