In [ ]:
##Creación y Indexación
#SECTION - 1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5

In [ ]:
import numpy as np

In [ ]:
# Crear un array 1D con 50 valores aleatorios entre 10 y 99
array_1d = np.random.randint(10, 100, 50)

# Acceder a los elementos en las posiciones múltiplos de 5
multiples_of_5 = array_1d[::5]

# Mostrar el array completo y los elementos en posiciones múltiplos de 5
print("Array 1D completo:")
print(array_1d)
print("\nElementos en posiciones múltiplos de 5:")
print(multiples_of_5)

In [ ]:
# 2. Crear un array 1D con 30 valores del 1 al 20 (ambos incluidos)
array_1d = np.random.randint(1, 21,size=30)

# Acceder a los elementos en las posiciones impares
impar_indices_elements = array_1d[1::2]

# Mostrar el array completo y los elementos en posiciones impares
print("Array 1D completo:")
print(array_1d)
print("\nElementos en posiciones impares:")
print(impar_indices_elements)

In [ ]:
# 3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estarcomprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimalesdeben estar redondeados a 2 decimales.

In [ ]:


# Crear un array 2D de forma (4, 6) con números aleatorios decimales entre 10 y 99
array_2d = np.random.uniform(10, 100, size=(4, 6))

# Redondear los decimales a 2 decimales
array_2d = np.round(array_2d, 2)

# Acceder a la última fila de la matriz
ultima_fila = array_2d[-1]

# Mostrar el array completo y la última fila
print("Array 2D completo:")
print(array_2d)
print("\nÚltima fila de la matriz:")
print(ultima_fila)


In [ ]:
# Crear un array 3D de forma (2, 3, 5) con números enteros entre 0 y 100 (ambos incluidos)
array_3d = np.random.randint(0, 101, size=(2, 3, 5))

# Aplanar el array para identificar las posiciones múltiplos de 3
flattened_array = array_3d.flatten()

# Identificar las posiciones múltiplos de 3
multiples_of_3_indices = np.arange(len(flattened_array))[::3]

# Reemplazar los valores en esas posiciones por 0.1
flattened_array[multiples_of_3_indices] = 0.1

# Reformar el array a su forma original
array_3d_modified = flattened_array.reshape((2, 3, 5))

# Mostrar el array original y el array modificado
print("Array 3D original:")
print(array_3d)
print("\nArray 3D modificado:")
print(array_3d_modified)

In [ ]:
##2. Reshape y Transpose
# Reshape
#1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambosinclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en laforma que es correcta para hacer este cambio

In [ ]:

# Crear un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos incluidos)
array_3d = np.random.randint(1, 101, size=(2, 3, 4))

# Convertir el array 3D en un array 2D utilizando reshape
# La forma 2D podría ser (6, 4) o (4, 6) ya que 2*3*4 = 24
array_2d = array_3d.reshape(6, 4)

# Mostrar el array original y el array convertido
print("Array 3D original:")
print(array_3d)
print("\nArray 2D convertido:")
print(array_2d)


In [ ]:
array_2d = array_3d.reshape(4, 6)

In [ ]:
#2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utilizareshape para convertirlo en un array

In [ ]:


# Crear un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir)
array_3d = np.arange(1, 61).reshape(3, 4, 5)

# Convertir el array 3D en un array 2D utilizando reshape
# La nueva forma 2D debe tener el mismo número de elementos (3 * 4 * 5 = 60)
array_2d = array_3d.reshape(5, 12)  # Por ejemplo, (12, 5)

# Mostrar el array original y el array convertido
print("Array 3D original:")
print(array_3d)
print("\nArray 2D convertido:")
print(array_2d)


Preguntas 

##3.Funciones Aritméticas y Estadísticas:

1. Diferencias entre reshape y tranporse
   Reshape- Cambiar el tamaño el arry
   Transpose= Cambiar los datos de lugar, transponiendo filas a columnas

2. Diferencias entre transpose y Swapaxis
En resumen, transpose puede reordenar múltiples ejes en un nuevo orden, mientras que swapaxes se limita a intercambiar dos ejes específicos. Ambas funciones son útiles para manipular la forma y la orientación de los datos en un array multidimensional.

In [ ]:
# 1. Crea un array de tres 3D con elementos entre el 0 y 1 de( 2fo, r3m, a5) cuyos valores solo tengan 1 decimal.

In [ ]:

# Crear un array 3D de forma (2, 3, 5) con valores aleatorios entre 0 y 1
array_3d = np.random.rand(2, 3, 5)

# Redondear los valores a 1 decimal
array_3d = np.round(array_3d, 1)

# Mostrar el array 3D
print("Array 3D con valores entre 0 y 1, redondeados a 1 decimal:")
print(array_3d)


#2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos
de crear pero basándonos en los valores del primer array bajo las siguientes
condiciones:
Si el valor del array es igual que la media, se reemplazAa" .por "
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".

In [16]:


# Crear un array 3D de forma (2, 3, 5) con valores aleatorios entre 0 y 1
array_3d = np.random.rand(2, 3, 5)

# Redondear los valores a 1 decimal
array_3d = np.round(array_3d, 1)

# Crear un array vacío con la misma forma y dimensiones que el array inicial
array_reemplazo = np.empty(array_3d.shape, dtype=str)

# Calcular la media, el máximo y el mínimo del array inicial
media = np.mean(array_3d)
maximo = np.max(array_3d)
minimo = np.min(array_3d)

# Reemplazar los valores en el array vacío basándonos en las condiciones dadas
array_reemplazo[array_3d == media] = 'A'
array_reemplazo[array_3d > media] = 'B'
array_reemplazo[array_3d < media] = 'C'
array_reemplazo[array_3d == maximo] = 'D'
array_reemplazo[array_3d == minimo] = 'E'

# Imprimir el array original y el array reemplazado
print("Array 3D original:")
print(array_3d)
print("\nArray 3D reemplazado:")
print(array_reemplazo)


Array 3D original:
[[[0.2 0.6 0.8 0.4 0.4]
  [0.3 0.5 0.6 0.  0.7]
  [0.9 0.7 0.2 0.8 0. ]]

 [[0.6 0.6 0.5 0.8 0.6]
  [0.2 0.5 0.7 0.9 0.9]
  [0.2 0.5 0.7 0.6 0.1]]]

Array 3D reemplazado:
[[['C' 'B' 'B' 'C' 'C']
  ['C' 'C' 'B' 'E' 'B']
  ['D' 'B' 'C' 'B' 'E']]

 [['B' 'B' 'C' 'B' 'B']
  ['C' 'C' 'B' 'D' 'D']
  ['C' 'C' 'B' 'B' 'C']]]


In [19]:
# Calcular la media, el máximo y el mínimo del array inicial
media = np.round(np.mean(array_3d))

np.round(array_3d, 1)

# Crear un array vacío con la misma
maximo = np.max(array_3d)
minimo = np.min(array_3d)

In [20]:
media


1.0

In [21]:
maximo

0.9

In [22]:
minimo

0.0

In [23]:
array_reemplazo[array_3d == media] = 'A'
array_reemplazo[array_3d > media] = 'B'
array_reemplazo[array_3d < media] = 'C'
array_reemplazo[array_3d == maximo] = 'D'
array_reemplazo[array_3d == minimo] = 'E'

In [24]:
array_reemplazo

array([[['C', 'C', 'C', 'C', 'C'],
        ['C', 'C', 'C', 'E', 'C'],
        ['D', 'C', 'C', 'C', 'E']],

       [['C', 'C', 'C', 'C', 'C'],
        ['C', 'C', 'C', 'D', 'D'],
        ['C', 'C', 'C', 'C', 'C']]], dtype='<U1')